language: node_js
node_js:
- 10.16.0
cache:
  directories:
  - node_modules
jobs:
  include:
  - stage: test
    script: sh ./ci/test.sh
  - stage: build
    script: npm run build
  - state: deploy
    script: sh ./ci/deploy.sh
before_install:
- openssl aes-256-cbc -K $encrypted_862f62ddd419_key -iv $encrypted_862f62ddd419_iv
  -in id_rsa.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa

